import type { Metadata } from 'next';
import Navigation from '@/components/navigation/Navigation';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navigation />
      <div
        className="w-screen flex items-center justify-center"
        style={{ height: 'calc(100dvh - 60px)' }}
      >
        {children}
      </div>
    </>
  );
}
